tiramisu:
    workspace: ./experiment_dir/workspace
    experiment_dir: ./experiment_dir/

code_deps:
    includes:
        - /home/ubuntu/install/include
    libs:
        - /home/ubuntu/install/lib

dataset:
    dataset_format: PICKLE
    cpps_path: ./data/cpps.pkl
    dataset_path: ./data/data.pkl
    save_path: ./experiment_dir/dataset
    shuffle: True
    seed: 13
    saving_frequency: 100
    # When doing evaluation on the benchmark set the value to True
    is_benchmark: False
    benchmark_cpp_files: ./data/old_benchmark_cpps.pkl
    benchmark_dataset_path: ./data/old_benchmark.pkl
    
experiment:
    legality_speedup: 1.0
    beam_search_order: true