tiramisu:
    workspace: /home/ubuntu/dev/gnn_rl/experiment_dir/workspace
    experiment_dir: /home/ubuntu/dev/gnn_rl/experiment_dir/

code_deps:
    includes:
        - /home/ubuntu/install/include
    libs:
        - /home/ubuntu/install/lib

dataset:
    dataset_format: PICKLE
    cpps_path: /home/ubuntu/dev/gnn_rl/data/cpps.pkl
    dataset_path: /home/ubuntu/dev/gnn_rl/data/data.pkl
    save_path: /home/ubuntu/dev/gnn_rl/experiment_dir/datasets
    shuffle: True
    seed: 13
    saving_frequency: 100
    # When doing evaluation on the benchmark set the value to True
    is_benchmark: False
    benchmark_cpp_files: /home/ubuntu/dev/gnn_rl/data/old_benchmark_cpps.pkl
    benchmark_dataset_path: /home/ubuntu/dev/gnn_rl/data/old_benchmark.pkl
    
experiment:
    legality_speedup: 1.0
    beam_search_order: true