tiramisu:
    tiramisu_path: path_to_tiramisu
    workspace: path_to_compile_workspace
    experiment_dir: path_to_experiment_dir

code_deps:
    includes:
        - 
    libs:
        - 

dataset:
    dataset_format: PICKLE
    cpps_path: path_to_cpp_files
    dataset_path: path_to_dataset
    save_path: path_to_save_dataset
    shuffle: True
    seed: 13
    saving_frequency: 100
    # When doing evaluation on the benchmark set the value to True
    is_benchmark: False
    benchmark_cpp_files: path_to_benchmark_cpp_files
    benchmark_dataset_path: path_to_benchmark_dataset
    
experiment:
    legality_speedup: 1.0
    beam_search_order: true